# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MfidyvzroO3b04Bx2jZFalEfBvNY7bB4
"""

# -*- coding: utf-8 -*-
"""3_way_splitting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xyNkFcSq9Qg5PK52GxhdkgPXXA5Je0c4
"""

import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv"
df = pd.read_csv(url, sep=';')

df['quality_label'] = (df['quality'] >= 7).astype(int)

X = df.drop(['quality', 'quality_label'], axis=1)
y = df['quality_label']

X_trainval, X_test, y_trainval, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y)

X_train, X_val, y_train, y_val = train_test_split(
    X_trainval, y_trainval, test_size=0.25, random_state=42, stratify=y_trainval)

rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)

y_val_pred = rf.predict(X_val)
val_acc = accuracy_score(y_val, y_val_pred)
print(f"Validation Accuracy: {val_acc:.4f}")

y_test_pred = rf.predict(X_test)
test_acc = accuracy_score(y_test, y_test_pred)
print(f"Test Accuracy: {test_acc:.4f}")

print("\nTest set classification report:")
print(classification_report(y_test, y_test_pred))