# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MfidyvzroO3b04Bx2jZFalEfBvNY7bB4
"""

# ✅ Logistic Regression with Probabilities (Two-Way Split)
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, roc_auc_score, classification_report

# Upload CSV in Google Colab
from google.colab import files
uploaded = files.upload()

# Load dataset
df = pd.read_csv(next(iter(uploaded)))
print(df.head())

# ✅ Change 'target' to your actual label column
X = df.drop('target', axis=1)
y = df['target']

# Two-way split: Train 80%, Test 20%
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Logistic Regression Model
model = LogisticRegression()
model.fit(X_train, y_train)

# ✅ Probability Predictions
y_prob = model.predict_proba(X_test)[:, 1]  # Probability of class 1
y_pred = (y_prob >= 0.5).astype(int)        # Convert to class labels

# ✅ Evaluation with probabilities
print("Accuracy:", accuracy_score(y_test, y_pred))
print("ROC-AUC Score:", roc_auc_score(y_test, y_prob))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

# ✅ Show first 10 probability results
results = pd.DataFrame({
    "Actual": y_test[:10].values,
    "Predicted Probability": y_prob[:10]
})
print("\nSample Probability Output:\n", results)